site_name: Coming Soon
site_url: https://www.trudat.co.za/
repo_url: null
site_description: Education For The World Of Tomorrow
site_author: various
theme: 
  name: mkdocs
  custom_dir: 'moak_theme/'
  nav_style: dark 




